#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : popt
Version  : 1.16
Release  : 10
URL      : http://rpm5.org/files/popt/popt-1.16.tar.gz
Source0  : http://rpm5.org/files/popt/popt-1.16.tar.gz
Summary  : popt library.
Group    : Development/Tools
License  : MIT
Requires: popt-lib
Requires: popt-locales
Requires: popt-doc
BuildRequires : gettext

%description
This is the popt(3) command line option parsing library. While it is similiar
to getopt(3), it contains a number of enhancements, including:

%package dev
Summary: dev components for the popt package.
Group: Development
Requires: popt-lib

%description dev
dev components for the popt package.


%package lib
Summary: lib components for the popt package.
Group: Libraries

%description lib
lib components for the popt package.


%package locales
Summary: locales components for the popt package.
Group: Default

%description locales
locales components for the popt package.


%package doc
Summary: doc components for the popt package.
Group: Documentation

%description doc
doc components for the popt package.


%prep
%setup -q -n popt-1.16

%build
%configure --disable-static 
make V=1 %{?_smp_mflags}  

%check
make V=1 %{?_smp_mflags} check
 
%install
rm -rf %{buildroot}
%make_install 
%find_lang popt

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files locales -f popt.lang 
%defattr(-,root,root,-)

